services:
  laraveladmin-database:
    image: mariadb
    restart: always
    container_name: laraveladmin-database
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laraveladmin-network
      - npm

  laraveladmin-phpmyadmin:
    container_name: laravel-admin
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=laraveladmin-database
    networks:
      - laraveladmin-network
      - npm
    depends_on:
      - laraveladmin-database

  laraveladmin-website:
    container_name: laraveladmin-website
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./website:/var/www/html
      - node_modules:/var/www/html/node_modules
    networks:
      - laraveladmin-network
      - npm
    # user: "1000:1000" #on my pc
    ports:
      - 5173:5173
    depends_on:
      - laraveladmin-database

volumes:
  db-data:
  node_modules:
networks:
  laraveladmin-network:
    driver: bridge
  npm:
    external: true
    name: npm
